### ISSUE TITLE
Push it even further?

### ISSUE THREAD

**Issue by 0z4** [cnlohr/nosdk8266#11]
How about sir, I have been watching this project for a while now and wanted to ask you some questions. At the moment my goal is to reach the maximum speed in the ESP8266, the only requirement is to have a stable UART connection, everything else like WiFi, GPIOs, etc ... can go away. The only thing I'm looking for is the maximum processing speed. My question is: Do you think we can push this over 360MHz? If yes, what do you estimate we can achieve?

I also forgot to mention that the truth is that I do not care about the size of the executable, but since Im searching to modify functions at such a low level and disable even the smallest thing that I do not need, I think that with this project I would be killing two birds with one shoot.

**Comment by cnlohr** [comment]
Sorry just seeing this after all these years - I don't know what speeds are actually possible.  I encourage experimentation.  I have been working on this a bit, and getting further.
