### ISSUE TITLE
Running at 1.848 GHz but without a UART connection?

### ISSUE THREAD

**Issue by 0z4** [cnlohr/nosdk8266#12]
So I was trying to get 462MHz to work playing with the PLL and MAIN_MHZ registers, when I tried to change the led blink rate in main.c, though, for the UART port I was getting only nonsensical garbage (probably because of the strange frequency of the PLL) The led behaved as I had specified, that is, the time between blinks changed. That was when I kept increasing the frequency periodically until I reached 1.848 GHz. I am not very excited by this discovery because surely you had already noticed it while working, but I am thinking, If i implement an I2C communication using GPIO and call_delay_us functions? What do you think about this?

Regards.

**Comment by cnlohr** [comment]
WHUT??? @0z4  I have no idea how this was possible.  Can you share more about your various settings?

**Comment by cnlohr** [comment]
Please also share any evidence you have surrounding this operation.  I was not able to get the chip to boot at all past the speeds I listed.

I am also incredibly curious what performance you were able to eek out of the I2S port.

**Comment by 0z4** [comment]
Well, check my fork, i map all possible PLL registers, after disabling the cache and the I2S, when you pass 378MHz the FLASH speeds explode, it can't divide any funther. :(
