### ISSUE TITLE
Change main frequency

### ISSUE THREAD

**Issue by Matheus-Garbelini** [cnlohr/nosdk8266#4]
Hello, i looked in the makefile and MAIN_MHZ is defaulted in 320Mhz. But it isn't in the freuency table you provided.
MAIN_MHZ in 320Hz configures a peripheral clock to 160Mhz?

**Comment by cnlohr** [comment]
Yep  Does it specify that incorrectly?

**Comment by Matheus-Garbelini** [comment]
Sorry, i'm new to ESP and development things. I asked just to be sure. Thank a lot by this repository and keep up with the good work.
