### ISSUE TITLE
Clock speed tests

### ISSUE THREAD

**Issue by mengstr** [cnlohr/nosdk8266#6]
I ran some performance tests for all the supported clock speeds and they all pretty much have a  spot on relative performance compared to a 52MHz base reading.  But the 189 MHz sticks out like a sore thumb ;-)

Any idea why?

|Mhz|Elapsed|Theoretical|Diff|
|---|---|---|---|
|52|134.61|x|x|		
|80|87.50|87.50|0.0|
|104|67.31|67.31|0.0|
|115|60.58|60.87|-0.3|
|160|43.75|43.75|0.0|
|173|40.38|40.46|-0.1|
|189|38.15|37.04|1.1|
|231|30.29|30.30|0.0|
|320|21.85|21.87|0.0|
|346|20.19|20.23|0.0|
|378|18.99|18.52|0.5|

The script for testing and the tested code are available  in the gist below if anyone is interested...
https://gist.github.com/mengstr/f625137ca053c97bd6f6bc5e1ea230c8

**Comment by cnlohr** [comment]
Yep. 1040 MHz/divisor.

~189 MHz is 1040/5.5.
